version: "3.2"
services:
  phpapache:
    build: './phpapache/'
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/
      - ./tesishojas/:/home/tesishojas/
      - ./tesiscompletas/:/home/tesiscompletas/
  mysql:
    #image: mysql:5.6.40
    build: './mysql/'
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database/:/var/lib/mysql/ 
  phpmyadmin:
    build: './phpmyadmin/'
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
networks:
  frontend:
  backend: